### ISSUE TITLE
Не пойму как перебрать данные в Соответствии

### ISSUE THREAD

**Issue by ret-Phoenix** [dmpas/oscript-component-example#3]
ScriptEngine.HostedScript.Library.MapImpl ChoiceList

foreach (var item in ChoiceList) ...

Суть: из скрипта передаю соответствие, в плагине требуется его перебрать и получить Dictinary<IValue, IValue>.

**Comment by dmpas** [comment]
``` C#
foreach (var ivItem in ChoiceList)  // ivItem типа IValue
{
  var item = ivItem as KeyAndValueImpl;
  var key = item.Key;
  var value = item.Value;
  ....
}
```

по этому вопросу уже есть заявка https://github.com/EvilBeaver/OneScript/issues/310

**Comment by ret-Phoenix** [comment]
Спасибо )
