### ISSUE TITLE
Запуск тестов под VisualStudio

### ISSUE THREAD

**Issue by dmpas** [dmpas/oscript-component-example#8]
В VisualStudio под 64-битной виндой упорно не хочет запускать тесты под AnyCPU.

**Comment by ret-Phoenix** [comment]
Как запускаешь тесты?
у меня везде только x64 Windows (7, 8.1, 10)

**Comment by dmpas** [comment]
Командой Run Unit Tests. Или с командной строки nunit3-console тоже не хочет AnyCPU, приходится ему `--x86` указывать явно. Притом, что в XamarinStudio под виндой всё отрабатывает.

**Comment by ret-Phoenix** [comment]
Для VisualStudio специализированных тестов не создавал. все тестирование проводил только на уровне oscript.

Или я что-то не так понимаю?

**Comment by dmpas** [comment]
Проект NUnitTests как-раз и сделан, чтобы создавать тесты ВНУТРИ среды разработки, без участия oscript. Тут два преимущества: можно отработать логику компоненты на уровне C#-объекта и можно запускать тесты CI-серверах.

**Comment by ret-Phoenix** [comment]
Готов учиться, где что в первую очередь читать? )

**Comment by dmpas** [comment]
Гуглить NUnit. а по данному проекту пока нет документации, только примеры.

**Comment by dmpas** [comment]
Решено: в окне запуска модульных тестов есть настройка "Platform", где можно явно задать "x86".
